name: Generate Contribution Snake

on:
  schedule:
    # Runs every 6 hours (UTC)
    - cron: "0 */6 * * *"
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed to push to the repository

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Required for the push action to work properly

      - name: Generate Snake
        uses: Platane/snk@v2
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          gif_out_path: assets/github-contribution-grid-snake.gif
          svg_out_path: assets/github-contribution-grid-snake.svg
          # Optional customization:
          # color: 'green'  # Change snake color
          # svg_width: 800  # Set SVG width
          # svg_height: 300 # Set SVG height

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add assets/
          git commit -m "Update contribution snake" || echo "No changes to commit"
          git push

      - name: Deploy to GitHub Pages (Optional)
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./assets
          destination_dir: ./snake
